name: BoilerPlate
main: net.ddns.vcccd.Main
version: 1.0.0
api-version: '1.21.1'
commands:
  boilerplate:
    description: An example command
    usage: /<command> <args>
    permission: boilerplate.example
